### ISSUE TITLE
MarkowitzModel expected input parameters

### ISSUE THREAD

**Issue by PhantomYdn** [optimatika/ojAlgo-finance#1]
Hello,

Unfortunately, it's not clear from documentation what kind of input data is expected for MarkowitzModel.
Signature for the constructor is the following:
```java
public MarkowitzModel(final BasicMatrix covarianceMatrix, final BasicMatrix expectedExcessReturns) {
```
So, is there expected returns calculated as `"today close"/"yesterday close"-1` or it's logarithmic return `ln("today close"/"yesterday close")`.
The same question is for covariance matrix: is it expecting co-variance between natural returns or logarithmic?

**Comment by apete** [comment]
That's not a question for "ojAlgo". You can calculate or estimate those values anyway you want. Read a book, use Google or whatever, about estimating return, volatility and correlations from historical data to learn how other people do it.

**Comment by PhantomYdn** [comment]
Hmm... That's exactly why I asked, because in MPT commonly logarithmic returns are used. But if use it the co-variance matrix after the following code becoming full of NaNs. But for naturals returns - it's OK. And as I said: in MPT it's commonly logarithmic returns are used.

```java
BasicMatrix coMatrix =  org.ojalgo.finance.FinanceUtils.makeCovarianceMatrix(cdsList,false);
```

**Comment by apete** [comment]
Each of the time series you feed to that method should contain the raw/original prices (values).

`  tmpSampleSet = SampleSet.wrap(tmpPrimitiveSeries.quotients().log().toDataSeries());`
