### ISSUE TITLE
Verify downloading Yahoo Finance historical data from different locations

### ISSUE THREAD

**Issue by apete** [optimatika/ojAlgo-finance#10]
It's now possible to download historical data from Yahoo Finance again. That is, it works for me....

I'm in Sweden. Possibly it works for everyone in the EU - I don't know - but I do know that it doesn't work if you're outside the EU (like Switzerland or India).

Please run this test case and report here if you have any new info regarding from where it works.

https://github.com/optimatika/ojAlgo-finance/blob/develop/src/test/java/org/ojalgo/finance/data/fetcher/YahooFetcherTest.java

If the test case fails then please debug to try and find out where/how it goes wrong. When you do that it's very helpful to run the http communication through a proxy that lets you see all requests, responses, cookies, redirects and whatever. One such tool that works great is Charles:

https://www.charlesproxy.com

It's a commercial product, but they offer a free trial.

**Comment by apete** [comment]
Verified that it does NOT work from Egypt.

The response to the "challenge" request that is supposed to set the B-cookie is not correctly handled. There is a set-cookie header, but it's not processed (cookie not stored).

In the EU Consent case this seems to be corrected by a later request/response - that's why it works. Have to figure out why the set-cookie header of the challenge-response is not processed.

**Comment by clisztian** [comment]
Hello, I can confirm that it does NOT work in Switzerland either.

**Comment by apete** [comment]
Thanks, It (still) works for me here in Sweden, and I guess that means it works from anywhere within the EU. If you like to make it work from "your location" you have to try to fix it yourself...
