### ISSUE TITLE
Travis's failing

### ISSUE THREAD

**Issue by alf239** [optimatika/ojAlgo-finance#2]
It seems that Travis has exactly the same problem as I had locally, 

> Downloading from apache-snapshots: `https://repository.apache.org/snapshots/org/ojalgo/ojalgo/45.0.0-SNAPSHOT/ojalgo-45.0.0-SNAPSHOT.jar`

Maybe it might make sense to depend on a fixed version?

Or, alternatively, do 

```
.before_script:
    - git clone https://github.com/optimatika/ojAlgo.git
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true  -f ojAlgo/pom.xml
```

in `travis.yml`?

**Comment by apete** [comment]
ojAlgo and ojAlgo-finance are tightly coupled. I think it makes sense to allow ojAlgo-finance to (sometimes) have a SNAPSHOT dependency on ojAlgo during development.

Your suggestion with "before_script" could be a good solution. I tried it, but couldn't get it to work. Should the '.' before 'before_script' be there?

**Comment by apete** [comment]
@alf239 Travis is no longer failing, but I never got that "before_script" to work. I believe I saw that it ran, but the results where not available/found when building the main artefact.
